

style:
  image: ghcr.io/vhotspur/helenos-build-env-base:v3.0.1
  script:
    - make ccheck

.build-template:
  image: ghcr.io/vhotspur/helenos-build-env-${IMAGE_ARCH}:v3.0.1
  script:
    - mkdir build && cd build
    - ../configure.sh ${PROFILE_NAME}
    - ninja image_path

build-ia32:
  extends: .build-template
  variables:
    IMAGE_ARCH: ia32
    PROFILE_NAME: ia32

