

style:
  image: ghcr.io/vhotspur/helenos-build-env-base:v3.0.1
  script:
    - make ccheck

.build-template:
  variables:
    IMAGE_VERSION: v3.0.1
  image: ghcr.io/vhotspur/helenos-build-env-${IMAGE_ARCH}:${IMAGE_VERSION}
  script:
    - echo PROFILE_NAME=${PROFILE_NAME}
    - echo IMAGE_ARCH=${IMAGE_ARCH}
    - echo IMAGE_VERSION=${IMAGE_VERSION}
    - ninja --version
    - mkdir build && cd build
    - ../configure.sh ${PROFILE_NAME}
    - ninja
    - ninja image_path

build-ia32:
  extends: .build-template
  variables:
    IMAGE_ARCH: ia32
    PROFILE_NAME: ia32

build-mips32-msim:
  extends: .build-template
  variables:
    IMAGE_ARCH: mips32
    PROFILE_NAME: mips32/msim
