name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: amd64
            profile: amd64
          - image: mips32
            profile: mips32/msim

    runs-on: ubuntu-latest
    container: "ghcr.io/vhotspur/helenos-build-env-${{ matrix.config.image }}:v3.0.0"
    continue-on-error: true

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build HelenOS
        run: |
          mkdir build
          cd build
          ../configure.sh ${{ matrix.config.profile }}
          ninja
          ninja image_path
